# Generated by Django 5.2.7 on 2025-10-21 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_contributor_project_contributor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='contributor',
            new_name='contributors',
        ),
    ]
