# Generated by Django 5.2.7 on 2025-10-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_contributor_project_contributors'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='subtitle',
            field=models.CharField(default='project', max_length=100),
            preserve_default=False,
        ),
    ]
