# Generated by Django 5.2.7 on 2025-11-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='summary',
            field=models.CharField(default='Summary', max_length=500),
            preserve_default=False,
        ),
    ]
