# Generated by Django 5.2.7 on 2025-12-19 10:04

from django.db import migrations, models

def convert_github_links(apps, schema_editor):
    ProjectLink = apps.get_model('projects', 'ProjectLink')

    ProjectLink.objects.filter(
        link_type='github'
    ).update(
        link_type="github_frontend"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_summary'),
    ]

    operations = [
        migrations.RunPython(convert_github_links),
        migrations.AlterField(
            model_name='projectlink',
            name='link_type',
            field=models.CharField(choices=[('live', 'Live Site'), ('github_frontend', 'GitHub (Frontend)'), ('github_backend', 'GitHub (Backend)'), ('github', 'GitHub Repository')], max_length=20),
        ),
    ]


