# Generated by Django 5.2.7 on 2025-12-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_projectlink_link_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='description1',
        ),
        migrations.AddField(
            model_name='project',
            name='description2',
            field=models.TextField(default='Lorem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='description3',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
