# Generated by Django 5.2.7 on 2025-10-29 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='category',
            field=models.CharField(default='Tech', max_length=100),
            preserve_default=False,
        ),
    ]
